name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 130.225.39.149 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYKEY }}

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@130.225.39.149 "cd /path/to/app && git pull && npm install && pm2 restart all"