name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 130.225.39.149 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYKEY }}

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@130.225.39.149 "cd DSF/PolicyAmendmentApp2/ && sudo -s && git pull && npm install && pm2 restart all"
